name: Draft a new release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write

    steps:
      # Checkout the release branch explicitly
      - uses: actions/checkout@v4

      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: 브랜치 이름 확인
        run: echo ${{ steps.branch-names.outputs.current_branch }}

      - name: 버전 정보 추출(from Branch Name)
        run: echo "TAG=$(echo '${{ steps.branch-names.outputs.current_branch }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV

  create-release:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create a GitHub release
        if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && contains(github.head_ref, '.')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG }}
          name: ${{ env.TAG }}
